# Build stage
ARG VITE_API_BASE_URL=http://localhost:8000/api/v1
FROM oven/bun:1.2.19 AS build
WORKDIR /app
COPY web-frontend/ .
RUN echo "VITE_API_BASE_URL=${VITE_API_BASE_URL}" > .env \
    && bun install \
    && bun run build

# Serve static
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
