name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ scout/sco-1-d886e992 ]
    paths:
      - 'web-frontend/**'
      - '.github/workflows/frontend-pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.19'
      - name: Build
        working-directory: web-frontend
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL || 'http://localhost:8000/api/v1' }}
          BASE_PATH: /casa_yousef/
        run: |
          echo "VITE_API_BASE_URL=${VITE_API_BASE_URL}" > .env
          bun install
          BASE_PATH=$BASE_PATH bun run build
          cp dist/index.html dist/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web-frontend/dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
