name: Trigger Render Auto Deploy

on:
  push:
    branches:
      - scout/sco-1-d886e992
  workflow_dispatch:

jobs:
  deploy-render:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger backend deploy (Render)
        if: ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK != '' }}
        run: |
          curl -fsSL -X POST "$RENDER_BACKEND_DEPLOY_HOOK"
        env:
          RENDER_BACKEND_DEPLOY_HOOK: ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}

      - name: Trigger frontend deploy (Render)
        if: ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK != '' }}
        run: |
          curl -fsSL -X POST "$RENDER_FRONTEND_DEPLOY_HOOK"
        env:
          RENDER_FRONTEND_DEPLOY_HOOK: ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}
